# web servers (bbs)
[webservers]
15.206.203.149

# database servers (bba)
[dbservers]
3.110.189.14

# variables for webservers
[webservers:vars]
ansible_user=ec2-user

# variables for dbservers
[dbservers:vars]
ansible_user=ubuntu
